### ISSUE TITLE
Cancel toast.loading("I am on the 🛣 way...") when no needed.

### ISSUE THREAD

**Issue by syahirudean** [ngneat/hot-toast#101]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[x] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

toast.loading("I am on the 🛣 way...")

Currently, the loading will appear for an x amount of time.

## Expected behavior

Any way to cancel it when the loading has been completed?

## What is the motivation/use case for changing the behavior?

To use it when 

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [x] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by shhdharmen** [comment]
You can use `ref` to close the toast. Ref: https://ngneat.github.io/hot-toast/#toast-ref
