### ISSUE TITLE
Observe closes even observable is still taking some time

### ISSUE THREAD

**Issue by MRisto** [ngneat/hot-toast#102]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
When i create an observe toast and add all the messages it works, when the duration for the load is small, but when i do this on a heavy task, which takes some time. It will close the window. The problem is i can't set the duration anywhere. They are fixed in the constants.

## Expected behavior
Let me set the loading timeout in the observe or in global. 

Or is there another option?

## What is the motivation / use case for changing the behavior?
I can't use the observe like this. The only way would be to use a normal toast and set the duration higher. And then update it manually.

## Environment

<pre><code>
Angular version: 13.0.0

Browser:
- [x] Chrome (desktop) version 98
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 16 
- Platform:  Windows

Others:

</code></pre>

**Comment by shhdharmen** [comment]
You can change the duration using [global config](https://github.com/ngneat/hot-toast#toastoptions).
