### ISSUE TITLE
How can I use Font Awesome icons

### ISSUE THREAD

**Issue by kdbruin** [ngneat/hot-toast#103]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[X] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

Icons are fixed as far I can tell.

## Expected behavior

Allow the use of other icons, in my case the Font Awesome icons.

## What is the motivation / use case for changing the behavior?

Consistent icon usage in the whole application

## Environment

<pre><code>
Angular version: 13.2.3

Browser:
All browsers
</code></pre>

**Comment by shhdharmen** [comment]
Try providing font-awesome icon in `icon` property. See this example: <https://ngneat.github.io/hot-toast/#emoji>
