### ISSUE TITLE
Using toast.observe with NGRX selectors

### ISSUE THREAD

**Issue by DinoSourcesRex** [ngneat/hot-toast#105]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[x] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

I am trying to get the `toast.observe` functionality to work while using NGRX selectors. I guess my RXJS knowledge is failing me here as I do not understand how this mechanism works.

My issue is that I have a selector with some specific data being returned and I need to know how to map that model into whatever it is that `toastService.observe` expects.

```typescript
    this.store.select(someSelectorWithData(dataKey))
    .pipe(this.toast.observe({
        loading: 'Loading...',
        success: 'Success!',
        error: 'Error.',
    }),
    )
    .subscribe();
```

The above is a simple subscription which returns some data of whatever type. The current behaviour just throws up a toast message with `success`, despite the observable not being erroring later on down the line. It seems like only the first value is what is looked at.

## Expected behavior

A slightly more in depth example / link in the docs for some further reading on what to do to get this to function would be great, so that people like me can fill the gap in their knowledge.

---

Any help would be appreciated!

**Comment by shhdharmen** [comment]
Can you create a stackblitz to showcase the issue?

**Comment by DinoSourcesRex** [comment]
> Can you create a stackblitz to showcase the issue?

Sure I'll set something up soon.

**Comment by DinoSourcesRex** [comment]
@shhdharmen Hey there.

I've created a repo which you should be able to access on StackBlitz via this link. https://stackblitz.com/github/DinoSourcesRex/hot-toast-observe

The repo itself is [here](https://github.com/DinoSourcesRex/hot-toast-observe) with some info on the readme on where I think the focus areas should be for anyone looking into this to offer insight.

**Comment by shhdharmen** [comment]
You need to add `catchError` operator. Please check example here: <https://ngneat.github.io/hot-toast/#observe>.

**Comment by DinoSourcesRex** [comment]
@adisreyaj I added `catchError((error)=>of(error)),` to `toast.effects.ts` line 53  and this did not fix the issue, the same problem is occuring.

**Comment by shhdharmen** [comment]
Check this fork: https://stackblitz.com/edit/github-xckhhw?file=src/app/store/toast/toast.effects.ts, line no 54.

**Comment by DinoSourcesRex** [comment]
Hi, yes that's what I have done but if you observe the actual behaviour it is not behaving as expected.

Currently:

1) Action is made to make the Http Request 
2) Action is made to create the Http Request in the store
3) Toast is made to observe the http request in the store
4) Toast is shown as "Done"
5) Http Request returns
6) Http Request is updated in the store

The expected behaviour is for item 4 in the list to occur at the end, after the Http Request is updated.

Any suggestions on how to achieve this?

**Comment by shhdharmen** [comment]
I don't think it's related to toast library. Please ask such question on stackoverflow.com.
