### ISSUE TITLE
Angular 14 - HotToastContainerComponent error

### ISSUE THREAD

**Issue by gleisonkz** [ngneat/hot-toast#109]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

Toast message stop working after upgrading

After upgrading to Angular 14, toast stop working because of HotToastContainerComponent.

![image](https://user-images.githubusercontent.com/48810597/171768417-b49fea22-e0e4-4c96-8880-9644e82b3f81.png)

<pre><code>
Angular version: 14.0.0

Browser:
- [X ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 16.14.0
- Platform:  Windows

</code></pre>

**Comment by shhdharmen** [comment]
Can you please create a GitHub repo with minimal code to reproduce that error?

**Comment by gleisonkz** [comment]
It think it was a problem with my Nx workspace, I deleted the entire repo, clone again and now it's working.
