### ISSUE TITLE
Missing config key and incorrect styles applied for Info toast messages

### ISSUE THREAD

**Issue by jsgopher** [ngneat/hot-toast#120]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

1. There is no custom config key available for toast type info in the ToastConfig Model.

    [https://github.com/ngneat/hot-toast/blob/master/projects/ngneat/hot-toast/src/lib/hot-toast.model.ts#L27](https://github.com/ngneat/hot-toast/blob/master/projects/ngneat/hot-toast/src/lib/hot-toast.model.ts#L27)

2. Custom styles for warning type toast are applied to info type toast.

    [https://github.com/ngneat/hot-toast/blob/master/projects/ngneat/hot-toast/src/lib/hot-toast.service.ts#L162](https://github.com/ngneat/hot-toast/blob/master/projects/ngneat/hot-toast/src/lib/hot-toast.service.ts#L162)

## Expected behavior

Custom config key for info type toast should be added and used for the respective toast.

## Minimal reproduction of the problem with instructions

Kindly refer to this [CodeSandbox](https://codesandbox.io/s/hot-toast-info-type-bug-lqubjs?file=/src/app/app.module.ts)

![image](https://user-images.githubusercontent.com/105229673/212370853-4f77bc0f-5acc-44f9-b5da-9b9a7239eeea.png)

## What is the motivation / use case for changing the behavior?

Expected styles are not applying to the toast messages

## Environment

<pre><code>
Angular version >= 15.0.0

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
</code></pre>

**Comment by shhdharmen** [comment]
@jsgopher do you want to create PR?
