### ISSUE TITLE
Adding hot-toast

### ISSUE THREAD

**Issue by nizalsha** [ngneat/hot-toast#122]
At first tried this

```
ng add @ngneat/hot-toast
Skipping installation: Package already installed
    ✅️ Added "@ngneat/overview
    🔍 Installing packages...
Cannot read properties of undefined (reading `'kind')`
```

Error: Module not found: Error: Package path ./public-api is not exported from package D:\development\development_repo\sw-slots-2203-2\node_modules\@ngneat\hot-toast (see exports field in D:\development\development_repo\sw-slots-2203-2\node_modules\@ngneat\hot-toast\package.json)

Again tried this

npm install @ngneat/overview@3.0.0 @ngneat/hot-toast@4

he result is same

Error: Module not found: Error: Package path ./public-api is not exported from package D:\development\development_repo\sw-slots-2203-2\node_modules\@ngneat\hot-toast (see exports field in D:\development\development_repo\sw-slots-2203-2\node_modules\@ngneat\hot-toast\package.json)

**Comment by shhdharmen** [comment]
Please recreate issue with all the details mentioned in issue template.
