### ISSUE TITLE
Dismiss button not visible in Angular 15

### ISSUE THREAD

**Issue by DavithkbY** [ngneat/hot-toast#123]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
The dismiss button is invisble in Angular 15, but still clickable. I am using tailwind but that shouldn't be an issue I think.

![ezgif com-video-to-gif](https://github.com/ngneat/hot-toast/assets/71630103/7525c251-07f6-47fb-9e4d-f56b739fb28e)

## Expected behavior
Dismiss button to be visible, maybe even add click to dismiss?

## Minimal reproduction of the problem with instructions
Set default behaviour to dismiss in app module in import

## Environment

<pre><code>
Angular version: 15.0.0

Browser:
- [X ] Chrome (desktop) version Latest
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ X] Edge version Latest
 
For Tooling issues:
- Node version: 19.4  
- Platform: Mac  

Others:

</code></pre>

**Comment by shhdharmen** [comment]
Can you please create repo or stackblitz to showcase your issue?
