### ISSUE TITLE
Hot Toast 4.1.0 doesn't includes style sheet

### ISSUE THREAD

**Issue by DiegoOrdonezBecerril** [ngneat/hot-toast#126]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## Current behavior
After install the package with ng add or npm install, project initialization, styles aren't applied, trying to add them, project fails because it doesn't found the style sheet.

## Expected behavior
Styles get applied after install

## Environment

<pre><code>
Angular version: 14.2.11

Browser:
- [X] Chrome (desktop) version 87
- [ ] Chrome (Android) version
- [ ] Chrome (iOS) version
- [ ] Firefox version
- [ ] Safari (desktop) version
- [ ] Safari (iOS) version
- [ ] IE version
- [ ] Edge version
 
For Tooling issues:
- Node version: 18
- Platform:  Windows
</code></pre>

**Comment by shhdharmen** [comment]
Please create a stackblitz to showcase the issue.

**Comment by luishcastroc** [comment]
can you please describe how are you adding the styles? are you using css or scss?

**Comment by DiegoOrdonezBecerril** [comment]
In styles.scss, i'm adding @use 'node_modules/@ngneat/hot-toast/src/styles/styles.scss', but in 'node_modules/@ngneat/hot-toast' dir src doesn't exists. So the element can't find variables like '--hot-toast-close-btn-align-self' used in styles.

**Comment by luishcastroc** [comment]
```json
"stylePreprocessorOptions": {
"includePaths": ["node_modules"]
},
```

try adding this to your project.json before the styles property and let me know if that helps

**Comment by luishcastroc** [comment]
> In styles.scss, i'm adding @use 'node_modules/@ngneat/hot-toast/src/styles/styles.scss', but in 'node_modules/@ngneat/hot-toast' dir src doesn't exists. So the element can't find variables like '--hot-toast-close-btn-align-self' used in styles.

```json
"stylePreprocessorOptions": {
"includePaths": ["node_modules"]
},
```

try adding this to your project.json before the styles property and let me know if that helps

**Comment by shhdharmen** [comment]
@DiegoOrdonezBecerril with version 4.1.0, you don't need to include styles separately. Everything is taken care with `ng add @ngneat/hot-toast@4`. If `ng add` command doesn't work, try below:
```bash
npm install @ngneat/overview@3.0.0 @ngneat/hot-toast@4
```
