### ISSUE TITLE
Height of toast is not updated after updateMessage method

### ISSUE THREAD

**Issue by jkune** [ngneat/hot-toast#127]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
Height of the toast is not updated after change its content. This resolves in overlapping when multiple toast are shown
![overlapping issue hot-toast](https://github.com/ngneat/hot-toast/assets/11456386/7da5b0e5-dfca-4b0c-bf68-02e485ef0ed8)

## Expected behavior
Toast height is calculate after update its content to show in a correct position in toast-container component

## Minimal reproduction of the problem with instructions
<pre><code>
// Creating 4 toast for overlapping demostration
for (let i in [...Array(4).keys()]) {
    // Create toast
    const toastRef = this.toast.loading("Displayed on a single line");

    // Update toast message after a delay
    setTimeout(() => {
        toastRef.updateMessage("Now i'm overlapping previous toast messages because i'm using more lines than before preventing user to see previous messages")
        toastRef.updateToast({ type: 'error' });
    }, 1000);
}
</code></pre>
## Environment

<pre><code>
Angular version: 14-15

Browser:
- [X] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
</code></pre>

**Comment by shhdharmen** [comment]
Please create stackblitz to showcase the issue.
