### ISSUE TITLE
Set different icons for different toasts in global config

### ISSUE THREAD

**Issue by Jobu08** [ngneat/hot-toast#128]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Expected behavior
Is there an option to set custom icon for _success_, _error_, _loading_... in global config. Do I have to set custom icon on each call for new toast when I wanna use it?

**Comment by shhdharmen** [comment]
Please check documentation.
