### ISSUE TITLE
Toaster does not show up with Error: No component factory found for HotToastContainerComponent

### ISSUE THREAD

**Issue by jaddap2** [ngneat/hot-toast#13]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ x] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
The Toaster not showing up but displays error `Error: No component factory found for HotToastContainerComponent`

## Expected behavior
Toaster should show up

## Minimal reproduction of the problem with instructions
Run the project https://stackblitz.com/edit/angular-3gyivx?file=src%2Fapp%2Fapp.module.ts

## Environment

<pre><code>
Angular version: 11.0.8

Browser:
- [ x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 14.x
- Platform:  Mac

<img width="485" alt="Screen Shot 2021-02-02 at 12 46 36 AM" src="https://user-images.githubusercontent.com/56288554/106557586-23c56600-64f0-11eb-91d3-aef5b35eb4e1.png">

**Comment by NetanelBasal** [comment]
@shhdharmen, please add it to the `entryComponents` list to support ViewEngine.

**Comment by jaddap2** [comment]
Got it. Also checking **Enable Ivy** checkbox on StackBlitz fixes the issue. 

However I can't get it to work on my project. I do not see any errors in console and I followed the instructions from docs. It's really strange, now I can't reproduce the issue in StackBlitz
