### ISSUE TITLE
Using observe with a component stuck in a loading state

### ISSUE THREAD

**Issue by avim101** [ngneat/hot-toast#134]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
Using observe with a component stuck in a loading state

## Expected behavior

Loading / Success / Error should work

## Minimal reproduction of the problem with instructions

https://stackblitz-starters-u7op8d.stackblitz.io
https://stackblitz.com/edit/stackblitz-starters-u7op8d?file=src%2Fmain.ts

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [X] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.19.3  
- Platform:  Mac 

Others:

</code></pre>

**Comment by avim101** [comment]
@NetanelBasal @shhdharmen 
Have you had a chance to take a look at the issue?
Thanks

**Comment by chrisweight-elsewhen** [comment]
Seeing the same issue as well, but using `.loading()` followed by `updateToast({ type: 'success' })`
