### ISSUE TITLE
SRC is missing

### ISSUE THREAD

**Issue by Applicafroguy** [ngneat/hot-toast#143]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
Compile error, 

When adding styles 
"styles": [
     "node_modules/@ngneat/hot-toast/src/styles/styles.css",
]

src does not exist.

## Minimal reproduction of the problem with instructions
Install version 4.x 
and add styles

"styles": [
     "node_modules/@ngneat/hot-toast/src/styles/styles.css",
]

src does not exist.

## Environment

<pre><code>
Angular version: 14

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 18.16.0  
- Platform:  Linux

**Comment by shhdharmen** [comment]
Can you create a stackblitz?
