### ISSUE TITLE
Build Failed depending @ngneat/overview@^6

### ISSUE THREAD

**Issue by dertuerke** [ngneat/hot-toast#147]
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report 
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
I have try to build, i get this error:
```
No matching export in "node_modules/@ngneat/overview/fesm2022/ngneat-overview.mjs" for import "DynamicViewModule"

    node_modules/@ngneat/hot-toast/fesm2022/ngneat-hot-toast.mjs:6:37:
      6 │ ...mplateRef, isComponent, DynamicViewModule } from '@ngneat/overvi...
```
They need to update the peer deps in this package from "ngneat/overview"

## Environment

<pre><code>
Angular version: 17.0.5
 
For Tooling issues:
- Node version: v18
- Platform:  Mac

Packages:
"@angular/animations": "^17.0.5",
"@angular/common": "^17.0.5",
"@angular/compiler": "^17.0.5",
"@angular/core": "^17.0.5",
"@angular/forms": "^17.0.5",
"@angular/platform-browser": "^17.0.5",
"@angular/platform-browser-dynamic": "^17.0.5",
"@angular/router": "^17.0.5",
"@ngneat/dialog": "^5.0.0",
"@ngneat/hot-toast": "^6.0.1",
"@ngneat/overview": "^6.0.0",
"rxjs": "~7.8.1",
"tslib": "^2.6.2",
"zone.js": "~0.14.2"
</code></pre>

**Comment by dertuerke** [comment]
> downgrade @ngneat/overview to v5.1.1

i want to upgrade my packages not downgrade ;)

**Comment by osahner** [comment]
absolutely! you probably should change the title to missing include DynamicViewModule from @ngneat/overview@^6, or upgrade to depending @ngneat/overview@^6

**Comment by NetanelBasal** [comment]
@shhdharmen please make the version stricter.

**Comment by joeskeen** [comment]
Is there any plans in the works to support `@ngneat/overview@6`? In addition to `@ngneat/hot-toast` I'm using `@ngneat/helipopper@9` which requires `@ngneat/overview@6`, so I'm currently in a position where there's not a possible resolution for that package.

**Comment by osahner** [comment]
Hm, 🤔 even version v6.0.2 has a peer dependency "@ngneat/overview@5.1.1"
