### ISSUE TITLE
Does not work with Bootstrap 4

### ISSUE THREAD

**Issue by osahner** [ngneat/hot-toast#21]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

As soon as Bootstrap 4 is added the Toast get invisible: 

https://codesandbox.io/s/musing-khayyam-83klg?file=/src/index.html

## Environment

<pre><code>
Angular version: ^10

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x] Firefox version XX
- [x] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

ng add does not work either:

```shell
app-test ng add @ngneat/hot-toast
Installing packages for tooling via yarn.
Installed packages for tooling via yarn.
An unhandled exception occurred: Cannot find module '@schematics/angular/utility/config'
```

and there is a undocumented dependency for @ngneat/overview

</code></pre>

**Comment by shhdharmen** [comment]
Please create separate issue for `ng add ...` not working.

Meanwhile, you can install using npm: `npm install @ngneat/overview @ngneat/hot-toast`

**Comment by shhdharmen** [comment]
This is producible. It's happening cz `toast` class is added and Bootstrap has `opacity: 0` set for `.toast`.

Will fix.

**Comment by osahner** [comment]
awesome!

**Comment by Anwar-ea** [comment]
I am using the package in my angular app it does not seems to show as the hot-toast website shows and even after setting duration and position it sticks in the left upper corner and does not fade away.

**Comment by shhdharmen** [comment]
@Anwar-ea please create separate issue with all the details.
