### ISSUE TITLE
Incorrect peer dependency versions

### ISSUE THREAD

**Issue by shhdharmen** [ngneat/hot-toast#28]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[x] Other... Please describe:
</code></pre>

## Current behavior

Please update versions in peer dependencies as follows:

```
    "@angular/common": "^8.2.14",
    "@angular/core": "^8.2.14",
    "@ngneat/overview": "^1.0.0"
```

**Comment by patdx** [comment]
Hi @shhdharmen, may I ask, is setting the peer dependency to Angular 8 supposed to mean `only supports Angular 8` or `supports Angular 8 or higher` ?

I tried this library in an Angular 11 app and got an error message when using the `ng update` command:

```
$ ng update @angular/core                          
Using package manager: 'pnpm'
Collecting installed dependencies...
Found 337 dependencies.
Fetching dependency metadata from registry...
                  Package "@ngneat/hot-toast" has an incompatible peer dependency to "@angular/common" (requires "^8.2.14" (extended), would install "11.2.5").
                  Package "@ngneat/hot-toast" has an incompatible peer dependency to "@angular/core" (requires "^8.2.14" (extended), would install "11.2.5").
✖ Migration failed: Incompatible peer dependencies found.
Peer dependency warnings when installing dependencies means that those dependencies might not work correctly together.
You can use the '--force' option to ignore incompatible peer dependencies and instead address these warnings later.
  See "/tmp/ng-XALEsV/angular-errors.log" for further details.
```

I can use --force command, so I don't mind so much.

But if this library supports up to Angular 11, maybe it's possible to give a more flexible peer dependency range instead?

For example: `>= 8.2.14 < 12`

https://jubianchi.github.io/semver-check/#/%3E%3D%208.2.14%20%3C%2012/11.0.0

**Comment by shhdharmen** [comment]
@patdx yes, it's supposed to mean 8 or higher. Do you want to generate PR with changes?

**Comment by patdx** [comment]
Hi @shhdharmen, thanks for the update. Sure, I submitted a PR here:

https://github.com/ngneat/hot-toast/pull/57

Please let me know if this will be alright? Thank you. 🙇

**Comment by shhdharmen** [comment]
Sure. Reopening this.
