### ISSUE TITLE
Installation error using ng add command

### ISSUE THREAD

**Issue by hexdecimal16** [ngneat/hot-toast#31]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[*] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

While installing using ng add feature I get this error 
`Cannot read property 'kind' of undefined`

## Expected behavior

Should add package without any issues.

## Minimal reproduction of the problem with instructions

 - run installation command:
  `ng add @ngneat/hot-toast`

## Environment

<pre><code>
Angular version: 11.0.2

Browser:
- [*] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v15.7.0  
- Platform: Linux

**Comment by shhdharmen** [comment]
I am not able to reproduce this in `v11.0.2`. Can you try again after uninstalling it? If it's still coming, can you please paste full error stack?

**Comment by hexdecimal16** [comment]
Okay, I will check and update you

**Comment by hexdecimal16** [comment]
Logs after again reinstalling

ng add @ngneat/hot-toast 
ℹ Using package manager: npm
✔ Found compatible package version: @ngneat/hot-toast@1.0.3.
✔ Package information loaded.
✔ Package successfully installed.
    ✅️ Added "@ngneat/overview
    🔍 Installing packages...
Cannot read property 'kind' of undefined`

**Comment by shhdharmen** [comment]
Why is it getting v1.0.3? Did you remove it from package.json before installing it again?

Can you create repo for code in which it's happening?

**Comment by hexdecimal16** [comment]
I just ran the command `ng add @ngneat/hot-toast`. Using npm method works perfectly fine.

**Comment by jongbonga** [comment]
> Using npm method works perfectly fine.

what does this mean?

I'm also getting the error on `@3.3.0`

**Comment by shhdharmen** [comment]
@jongbonga try to follow below steps:

1. Remove `@ngneat/hot-toast` from `package.json`
2. Run `npm i`
3. Run `ng add @ngneat/hot-toast`
