### ISSUE TITLE
Toast contents alignment issue in Firefox

### ISSUE THREAD

**Issue by adisreyaj** [ngneat/hot-toast#33]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
The vertical alignment of the toast contents:
- Icon
- Message
- Close button
are not centered.

This issue is identified in Firefox, Chrome seems to center things out properly.

![image](https://user-images.githubusercontent.com/29002760/107117445-73b17d80-68a0-11eb-855e-6c14144ac0da.png)

## Expected behavior
The contents should be vertically aligned.

## Minimal reproduction of the problem with instructions
Try any toast from the [Demo Page](https://ngneat.github.io/hot-toast/#examples) in Firefox.

## Environment

<pre><code>
Angular version: 11.1

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x] Firefox version 85.0
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

**Comment by adisreyaj** [comment]
Is the demo site updated as well?

**Comment by shhdharmen** [comment]
Yes

**Comment by shhdharmen** [comment]
Still some work is needed for this.

**Comment by shhdharmen** [comment]
Reverting this, as it's causing issues in case of multiline. Let's keep this open until I find the solution.

Meanwhile, you can override the styles of icon with help of `.hot-toast-icon` and `.hot-toast-close-btn` classes.

**Comment by shhdharmen** [comment]
Closing this as it's no longer an issue in latest version of firefox, i.e. `91.0 (64-bit)`.

![image](https://user-images.githubusercontent.com/6831283/128976752-08eb2e6b-c4c6-4e00-b612-b81eede19eed.png)
