### ISSUE TITLE
HotToastModule breaks router transition animations

### ISSUE THREAD

**Issue by scaljeri** [ngneat/hot-toast#38]
I think I've found a bug in the HotToastModule. The issue I have is that I'm using router transition animation, but as soon as I load this module they stop working (no animated transition anymore, just instant transitions)

I've create a [Stackblitz](https://stackblitz.com/edit/angular-ivy-6od29z?file=src%2Fapp%2Fapp.module.ts) to reproduce the issue.

In its current state the stackblitz imports HotToastModule. You can remove it to see the transitions work again. 

Could this be a bug in HotToastModule?

**Comment by shhdharmen** [comment]
As it was breaking existing features, reverted the fix. We will look into this again.
