### ISSUE TITLE
hot-toast support for Angular version 7.x.x

### ISSUE THREAD

**Issue by DeepakMohanSingh** [ngneat/hot-toast#39]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[x] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

I try to npm install using npm install @ngneat/overview @ngneat/hot-toast. I am able to install it but then it asks me to install the dependencies like @angular/common@^8.2.14, @angular/core@^8.2.14. The ng serve fails as expected with ambient context errors. The below is the actual error:

> ERROR in node_modules/@ngneat/hot-toast/lib/components/hot-toast/hot-toast.component.d.ts(14,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@ngneat/hot-toast/lib/components/hot-toast/hot-toast.component.d.ts(57,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@ngneat/hot-toast/lib/components/hot-toast/hot-toast.component.d.ts(58,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@ngneat/hot-toast/lib/hot-toast-ref.d.ts(11,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@ngneat/hot-toast/lib/hot-toast.model.d.ts(204,35): error TS2304: Cannot find name 'Omit'.
node_modules/@ngneat/hot-toast/lib/hot-toast.model.d.ts(204,40): error TS2304: Cannot find name 'Omit'.
node_modules/@ngneat/hot-toast/lib/hot-toast.model.d.ts(205,41): error TS2304: Cannot find name 'Omit'.
node_modules/@ngneat/hot-toast/lib/hot-toast.model.d.ts(205,46): error TS2304: Cannot find name 'Omit'.
node_modules/@ngneat/hot-toast/lib/hot-toast.service.d.ts(9,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@ngneat/hot-toast/lib/hot-toast.service.d.ts(10,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@ngneat/overview/lib/dynamic-content/dynamic-content.component.d.ts(10,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@ngneat/overview/lib/dynamic-content/dynamic-content.component.d.ts(13,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@ngneat/overview/lib/template-or-string/template-or-string.module.d.ts(5,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@ngneat/overview/lib/views/comp-ref.d.ts(14,9): error TS1086: An accessor cannot be declared in an ambient context.

## Expected behavior

May I know if there's a way to install and use hot-toast for an Angular version like 7.x.x?

## What is the motivation / use case for changing the behavior?

Toast support for an Angular version of 6 or 7 and above will benefit many users like me and mainly requesting a support request for version 7.

## Environment

<pre><code>
Angular version: 7.3.9

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

**Comment by shhdharmen** [comment]
I don't think we can provide support for v7 as of now. Hot-toast has dependency on [`@ngneat/overview`](https://www.npmjs.com/package/@ngneat/overview), and if I am not wrong, it doesn't support v7.

@NetanelBasal thoughts?

**Comment by NetanelBasal** [comment]
Sorry, but Angular v7 is too old. You're welcome to upgrade and use this library.
