### ISSUE TITLE
angular universal issue : document is not defined

### ISSUE THREAD

**Issue by PoulaHelmy** [ngneat/hot-toast#47]

**Comment by NetanelBasal** [comment]
Please provide a reproducible example.

**Comment by PoulaHelmy** [comment]
> Please provide a reproducible example.

![image](https://user-images.githubusercontent.com/43091492/109488735-a2310b80-7a8e-11eb-985a-a6ef2982f5cf.png)

**Comment by NetanelBasal** [comment]
https://github.com/ngneat/hot-toast/blob/master/projects/ngneat/hot-toast/src/lib/hot-toast.service.ts#L210

**Comment by PoulaHelmy** [comment]
thanks for your interest and reply to me.
but what problem with me, or what should I do with an error like that?
actually, I beginner with angular and don't know what should I do
