### ISSUE TITLE
Feature: HTML in the message without creating a lot of templates.

### ISSUE THREAD

**Issue by Local9** [ngneat/hot-toast#48]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

Currently the default method of the toast message doesn't support HTML, and the template method would require writing a lot of templates for simple HTML content to be displayed.

## Expected behavior

The toast service message can accept HTML Content, this will allow simple styling of the content. Maybe even allow a way to get the toast message in the template method?

## What is the motivation / use case for changing the behavior?

Not writing 10+ templates for simple messages that require parts of the content to be highlighted, and I'd rather support this as its cleaner and nicer than using ngx-toastr.

IF there is already a method for this, which I cannot find in the demos, please do direct me to it.

**Comment by NetanelBasal** [comment]
Seems reasonable to me.

**Comment by NetanelBasal** [comment]
Actually, it already works out of the box.

**Comment by Local9** [comment]
Now I see that I asked the wrong thing in my request; HTML is supported but style attribute is not, yet classes do work fine (which is a better approach). Sorry for wasting your time.
