### ISSUE TITLE
HttpClient call error loading handler

### ISSUE THREAD

**Issue by blueiceprj** [ngneat/hot-toast#50]
## When I use httpclient service and error return than loading toast not properly closing.

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Expected behavior
If you add this line in toast service class than running properly 

source.pipe(
                tap({
                    next:
.......
.......
......

,
                catchError(
                    (error: HttpErrorResponse): Observable<any> => {
                        toastRef.close();
                        return throwError(error);
                    },
                )

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [X] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by shhdharmen** [comment]
@blueiceprj can you add some minimum code which is causing the issue? Or create a stackblitz?

**Comment by blueiceprj** [comment]
I have global error handler and http intercepter class. When I call a rest end-point by httpclient service than return error from backend service. But "tap" cannot handle http error. To catch error have to add a new pipe "catchError" and throw error to global error handler class. I have to write new implementation of this method like that.


`


        observe<T>(loadingMessage: string, successMessage?: string, errorMessage?: string): 
       (source: Observable<T>) => Observable<T> {
        return (source) => {
            let overlayRef: OverlayRef;
            let toastRef: CreateHotToastRef;
            const config: ToastOptions = { ...this.toast.defaultConfig };

            if (loadingMessage) {
                config.style = {
                    'padding-top': '20px',
                    'padding-bottom': '20px',
                    'padding-left': '16px',
                    'padding-right': '16px',
                    'width': 'auto',
                    'max-width': 'var(--hot-toast-max-width,500px)',
                    'font-size': '16px',
                    'box-shadow': '0 3px 5px -1px rgb(0 0 0 / 20%), 0 6px 10px 0 rgb(0 0 0 / 14%), 0 1px 18px 0 rgb(0 0 0 / 12%)'
                };

                config.position = 'bottom-right';
                config.autoClose = true;
                config.id = UUID.UUID();
                config.dismissible = false;
                toastRef = this.toast.loading(loadingMessage, config);
                overlayRef = this.showOverlay();
            }

            return source.pipe(
                tap({
                    next: (val) => {
                        toastRef.close();
                        this.hideOverlay(overlayRef);
                        if (successMessage) {
                            this.success(successMessage);
                        }
                    },
                    ...(errorMessage && {
                        error: (e) => {
                            toastRef.close();
                            this.hideOverlay(overlayRef);
                            this.error(errorMessage);
                        },
                    }),
                })
                ,
                catchError(
                    (error: HttpErrorResponse): Observable<any> => {
                        toastRef.close();
                        this.hideOverlay(overlayRef);
                        return throwError(error);
                    },
                )
            );
        };
    }`

**Comment by shhdharmen** [comment]
I am still not getting what's the issue here and how it's related to hot-toast!

By the way, we have custom rxjs operator for such cases, checkout example at: <https://ngneat.github.io/hot-toast/#observe>
