### ISSUE TITLE
Options for Service.observe

### ISSUE THREAD

**Issue by Coly010** [ngneat/hot-toast#64]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

The `observe` function does not allow passing a config object.
https://github.com/ngneat/hot-toast/blob/c174e7e04e88ca0fa03c9bd7aba6c046c44fe636/projects/ngneat/hot-toast/src/lib/hot-toast.service.ts#L156

## Expected behavior

We should be able to pass config options similar to:
https://github.com/ngneat/hot-toast/blob/c174e7e04e88ca0fa03c9bd7aba6c046c44fe636/projects/ngneat/hot-toast/src/lib/hot-toast.service.ts#L66

**Comment by shhdharmen** [comment]
You can pass config for each state:

```typescript
this.toast.observe({
    loading: { content: "Preparing toast", style: { width: "200px" }, icon: '⏳' },
}),
```
