### ISSUE TITLE
Broken in angular 11

### ISSUE THREAD

**Issue by mehrad-meraji** [ngneat/hot-toast#65]
## I'm submitting a bug

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

After installing angular stops working with the error:

```
    core.js:1141 Uncaught Error: Type MatIconModule does not have 'ɵmod' property.
    at getNgModuleDef (core.js:1141)
    at recurse (core.js:25232)
    at recurse (core.js:25243)
    at recurse (core.js:25243)
    at recurse (core.js:25243)
    at recurse (core.js:25243)
    at recurse (core.js:25243)
    at registerNgModuleType (core.js:25228)
    at new NgModuleFactory$1 (core.js:25342)
    at compileNgModuleFactory__POST_R3__ (core.js:28976)
```

## Environment

<pre><code>
Angular version: 11.2.7

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v14.15.5  
- Platform: Mac

**Comment by shhdharmen** [comment]
Your error log has issue in  `MatIconModule`. I am not sure how it's related to hot-toast.

Can you give more explanation?

**Comment by mehrad-meraji** [comment]
no idea.. we moved on from this library, thank you
