### ISSUE TITLE
Set default options in .forRoot()

### ISSUE THREAD

**Issue by MickL** [ngneat/hot-toast#69]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[X] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

We need to set the position each time:

```ts
this.toast.error('hello world, {
    position: 'bottom-right'
});

```
## Expected behavior

Set default options in .forRoot():

```ts
imports:      [
   // ...
   HotToastModule.forRoot({position: 'bottom-right'}),
],
```

**Comment by shhdharmen** [comment]
Are you sure setting default options not working in forRoot?

**Comment by MickL** [comment]
I double checked:

```ts
imports:      [
   // ...
   HotToastModule.forRoot({position: 'bottom-right'}),
],
```

Then using:

```ts
this.toast.error('hello world');
```

And the position it top centered.

**Comment by shhdharmen** [comment]
I created a stackblitz and it's working fine: https://stackblitz.com/edit/angular-ivy-dvcjcn?file=src/app/app.module.ts.

**Comment by MickL** [comment]
I dont know what to say because the code you put in the stackblitz is exactly what I did, nothing more. Still it is not working for me. I am on Angular 12 if that counts.

**Comment by MickL** [comment]
I am doing the import  `HotToastModule.forRoot({position: 'bottom-right'}),` within a lazy loaded module (I only need toast in that module). Maybe thats the cause?
