### ISSUE TITLE
Feature request: Create positions as per user input

### ISSUE THREAD

**Issue by tarangrathod** [ngneat/hot-toast#71]
##  Can we create toast positions as per user input but passing top and bottom properties ?

- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report  
- [ ] Performance issue
- [x] Feature request 
- [ ] Documentation issue or request
- [ ] Support request
- [ ] Other... Please describe:

## Current behavior
When ever we create a toast it has only 6 positions either on top or bottom of screen on y axis in 3 different positions on x axis

## Expected behavior
Can we put come custom postilions as an input value so it can be provided as parameters in the options. 

## What is the motivation / use case for changing the behavior?
In the application there is some more stuff already coming in the place where toast is appearing and I want to change  toast position. 

## Environment

Angular version: 11+

Browser:
- [x] Chrome (desktop) version 90.0.4430.212
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [x] Edge version 90.0.818.66

**Comment by shhdharmen** [comment]
It's easily achievable through CSS. Let's say, you want to start placing toasts from `left: 20px; top: 100px`, you would follow below steps:

1. Set the global position to `HotToastModule.forRoor({ position: 'top-left' })`
2. Add following in the CSS:

```css
.hot-toast-bar-base-container {
  left: 20px !important;
  top: 100px !important;
}
```

I have created a sample app on stackblitz: https://stackblitz.com/edit/angular-ivy-mi6bxp?file=src/styles.css
