### ISSUE TITLE
All CSS properties not working in className.

### ISSUE THREAD

**Issue by mrtanishqbhatia** [ngneat/hot-toast#74]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

I am using className: "abc".
CSS:
.abc {
background-color: #00FF00,
width: 500px,
height: 100px,
margin: 10px 5px 15px 20px,
padding: 24px
}

The toast shown has still the default background (white) and default width, height and all the other properties defined in above CSS.

## Expected behavior

Support all CSS tags or support HTML and CSS layout so that toast can look any way we provide.

## Minimal reproduction of the problem with instructions
Define a toast with ToastOptions having className.
Define that class in CSS having background-color and all others.

## What is the motivation / use case for changing the behavior?

Toast can have any layout which makes it easier to customize. I cannot find any example having custom CSS file using various properties/tags like background-color, padding, margin, width, height, etc.

## Environment
Angular (typescript)
<pre><code>
Angular version: ^12.0.0

Browser:
- [91.0] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 14.xx  
- Platform: Windows 

Others:

Style supports some tags but not the tags with multiple words like background-color.
Also, what if I only want to give right padding to the icon but not div tags?
Please help me by either looking into this or redirecting me to an example using className having most CSS properties/tags.
</code></pre>

**Comment by shhdharmen** [comment]
I don't think this is an issue, you need to override properties with `!important` keyword.
