### ISSUE TITLE
Feature request: Limit visible toasts

### ISSUE THREAD

**Issue by davayd** [ngneat/hot-toast#77]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

Multiple times clicking creates uncontrolled size of toasts

![image](https://user-images.githubusercontent.com/17270614/127163323-11826075-1648-4427-b4cc-c01da3e3f319.png)

## Expected behavior
I am wondering if it is possible to control amount of visible toasts and show only [1,2,3, etc] toasts at the same time in toast stack

## Minimal reproduction of the problem with instructions
Clicking multiple times on button "Info" (https://ngneat.github.io/hot-toast/#info)
## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [x] Chrome (desktop) version XX
- [x] Chrome (Android) version XX
- [x] Chrome (iOS) version XX
- [x] Firefox version XX
- [x] Safari (desktop) version XX
- [x] Safari (iOS) version XX
- [x] IE version XX
- [x] Edge version XX
 
For Tooling issues:
- Node version: 14  
- Platform: Windows 

Others:

</code></pre>

**Comment by shhdharmen** [comment]
I don't know why someone would simply keep buttons to show the toasts. Toasts are supposed to give only needed information and only for a few seconds.

If you have uncontrolled amount of toasts appearing, then I would say you have to control it from your code.
