### ISSUE TITLE
Feature Request: Add default action and callback...

### ISSUE THREAD

**Issue by bvkimball** [ngneat/hot-toast#8]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Expected behavior

This library is great but like most other toast libraries I find them lacking an action button and callback, which i think is a common requirement when using a toast or snackbar, unless i missed it.  I know this could be implemented by using a custom template, but i think it should be part of the default behaior.

For example:
![image](https://user-images.githubusercontent.com/1056055/106528759-47b88580-64b7-11eb-865e-99ba3dcdfcfc.png)

Just My Opinion

**Comment by shhdharmen** [comment]
@NetanelBasal thoughts?

Action button can be added, but I think all users will end up writing their custom styles for button, so that it looks like their app's style guide.

In such cases, templates are the right way.

**Comment by NetanelBasal** [comment]
@bvkimball Are you talking about the snackbar variation?

**Comment by bvkimball** [comment]
@NetanelBasal I was talking about both variation.  I see it more common in SnackBars (ie material), In my apps we have Growls, Toasts, Banners & Snackbars and always need to add a default action ( Not for all toasts but some )

@shhdharmen I agree and disagree,  I think the SnackBar is becoming a common paradigm that a lot of UI systems are adopting both as a pattern and stylistically (if thats a word), because it is easily recognizable concept to the user. Less so for regular toast.

The request was just Food for Thought.

**Comment by NetanelBasal** [comment]
In the `toast` variation, it doesn't make a lot of sense to me. In the `snackbar` variation, it could be an option. Let's keep it open and see the demand for this feature.

**Comment by joeskeen** [comment]
@shhdharmen you closed this as completed. Is there now a way to add an action/callback to a toast/snackbar? I played around a bit and didn't see any examples or anything obvious in the API about how to accomplish this.
