### ISSUE TITLE
Regression when updating to v3.3

### ISSUE THREAD

**Issue by NetanelBasal** [ngneat/hot-toast#81]
<img width="651" alt="Screen Shot 2021-08-04 at 21 39 01" src="https://user-images.githubusercontent.com/6745730/128236354-ae7e223a-ac2e-4c07-9d9c-afe44c2665c2.png">
<img width="1070" alt="Screen Shot 2021-08-04 at 21 39 14" src="https://user-images.githubusercontent.com/6745730/128236388-0defdbd7-7abd-40b3-a035-e5c1ff9ae2c0.png">

The border color should be at the end.

**Comment by shhdharmen** [comment]
Just to confirm, you're setting the CSS custom property, but it's not reflecting in toast, right? For example, below is set, but success toast icon is still the default white:

```css
:root {
  --check-secondary: black;
}
```

**Comment by NetanelBasal** [comment]
No, I was just updateding from v3.1.0 without modifying anything.

**Comment by mrtanishqbhatia** [comment]
Even I am facing this half check mark in black color.
I am using default success with no CSS custom properties.
Just this.toast.success("Hello")
and the check is half white and half black.
