### ISSUE TITLE
No Provider for HotToastService

### ISSUE THREAD

**Issue by RayMckaig** [ngneat/hot-toast#82]
When I first tried to install Hot-Toast I had Angular 8.1.12 installed, and based on the dependency information during installation, which reported it required at least 8.2.14, I updated my version to the latest minor version of v8 which is 8.2.14.

I still had a few errorsafter that  which were all similar and were resolved by adding the option **"skipLibCheck": true** to the compilerOptions section in tsconfig.json, an example of which is:

**ERROR in ../node_modules/@ngneat/hot-toast/lib/components/hot-toast/hot-toast.component.d.ts:19:9 - error TS1086: An accessor cannot be declared in an ambient context.

19     get containerPositionStyle(): {**

I've also added **HotToastModule.forRoot()** to the imports section in app.module.

All compiled fine and the application ran up ok.

In one of my components, as a test. I added **private _toast: HotToastService** to the constructor, and used the following to test a toast:

**this._toast.success("Data Fields have been refreshed");**

Before it gets to this code however, simply displaying the component causes the following error to be output to Chrome tools:

**ERROR NullInjectorError: StaticInjectorError(AppModule)[SearchComponent -> HotToastService]: 
  StaticInjectorError(Platform: core)[SearchComponent -> HotToastService]: 
    NullInjectorError: No provider for HotToastService!**

If I add "HotToastService" to the providers list in app.module, the service mentioned in the error changes to "ViewService".

Now, I realise adding to the providers list already goes beyond the installation steps detailed, so I'm wondering if I'm doing something wrong?

**Comment by shhdharmen** [comment]
Due to multiple dependencies, we can't support Angular v8.
