### ISSUE TITLE
Success toast check/tick not in white color

### ISSUE THREAD

**Issue by mrtanishqbhatia** [ngneat/hot-toast#84]
## I'm submitting a...

<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
The success toast is displaying the check/tick mark in half white and half black color.

## Expected behavior
The success toast displays white check/mark.

## Minimal reproduction of the problem with instructions
After importing use the below lines:
`import { HotToastService } from '@ngneat/hot-toast';

@Component({})
export class AppComponent {
  constructor(private toast: HotToastService) {
    this.toast.success('Yeah!!');
  }
}

## What is the motivation / use case for changing the behavior?

Revert default white check mark

## Environment

<pre><code>
Angular version: 12.2.0

Browser:
- [92] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 16.6.0  
- Platform: Windows 

Others:

Using:
"@ngneat/hot-toast": "^3.4.0",
"@ngneat/overview": "^2.0.2",
Please refer to the images attached.
No custom styling (CSS/HTML/templates) has been used.
</code></pre>
![temp](https://user-images.githubusercontent.com/43254711/128942740-28f09040-6e7e-4b4a-8495-33711c50d9be.PNG)
![Untitled](https://user-images.githubusercontent.com/43254711/128942742-fe2b7d24-c4da-479d-9bdd-f3c791df3c2c.png)

**Comment by mizzyexists** [comment]
2nding this. Not sure why the check is half white / half black.

Only finding this issue with the green checkmark.

**Comment by mizzyexists** [comment]
Its a CSS issue. I have made note of it here.

CSS:
```
.hot-toast-checkmark-icon[_ngcontent-nhq-c23]::after {
    animation: var(--hot-toast-checkmark-icon-after-animation,hotToastCheckmarkAnimation .2s ease-out forwards);
    animation-delay: var(--hot-toast-checkmark-icon-after-animation-delay,.2s);
    border-bottom: var(--hot-toast-checkmark-icon-after-border-bottom,2px solid);
    border-color: var(--hot-toast-checkmark-icon-after-border-color,var(--check-secondary,#fff));
    border-right: var(--hot-toast-checkmark-icon-after-border-right,2px solid); **<----- PROBLEM IS HERE**
    bottom: var(--hot-toast-checkmark-icon-after-bottom,6px);
    box-sizing: var(--hot-toast-checkmark-icon-after-box-sizing,border-box);
    content: var(--hot-toast-checkmark-icon-after-content,"");
    height: var(--hot-toast-checkmark-icon-after-height,10px);
    left: var(--hot-toast-checkmark-icon-after-left,6px);
    opacity: var(--hot-toast-checkmark-icon-after-opacity,0);
    position: var(--hot-toast-checkmark-icon-after-position,absolute);
    width: var(--hot-toast-checkmark-icon-after-width);
```

**Comment by shhdharmen** [comment]
I am working on it, duplicate issue #81 .
