### ISSUE TITLE
Feature Request: durationUntilClose / setTimeout

### ISSUE THREAD

**Issue by RyannGalea** [ngneat/hot-toast#86]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[X] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

Current duration option seems to be a total duration, in the instance where I create a loading toast, and then update the status & type after a server call, I'd like to update the duration / duration until it closes.

Currently if I update the duration, it closes at unknown times because of the server call. eg:

```   
 const toast = this.ts.loading('Updating Job Status')
 await request()  
 toast.updateMessage('Status Updated')
 toast.updateToast({type: 'success', duration: 3000})
```

If I update the duration currently, the server call may already have taken the 3 seconds and it will automatically close giving no feedback of the success, or depending on the server call be inconsistent after the success state is set.

## Expected behavior

I'd like to see a durationUntilClose or similar that overrides duration, once the server call has processed, I set the type, and the durationUntilClose so I can always be sure the user sees the success state for the amount of time set.

```   
 const toast = this.ts.loading('Updating Job Status')
 await request()  
 toast.updateMessage('Status Updated')

 toast.updateToast({type: 'success', durationUntilClose: 3000})
or
 toast.updateToast({type: 'success', setTimeout: 3000})
```

**Comment by shhdharmen** [comment]
For such scenarios, we have created operator called `observe`, why don't you try that? For example visit this link: <https://ngneat.github.io/hot-toast/#observe>

**Comment by RyannGalea** [comment]
I have seen this in the docs but in this situation, it seems overly complex to use observables and templates. For something so simple at least.

I guess my initial thought is that updating the duration would reset the duration from that point in time, not simply adjust the existing time left & in some cases provide an undesirable close time.

**Comment by shhdharmen** [comment]
I am not sure whether we should add this feature, not at-least in options. Maybe we can add a method in `toastRef`, like `addDuration(duration: number)`.

But I don't think people will use this feature a lot. Let's keep this issue open and see, if it's in demand, we will consider it.

**Comment by RyannGalea** [comment]
Sounds good, Thanks for taking a look.
