### ISSUE TITLE
'DynamicViewDirective' is neither 'ComponentType' or 'DirectiveType'

### ISSUE THREAD

**Issue by hexdecimal16** [ngneat/hot-toast#95]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>
## Current behavior
Not able to use taost on angular 13
## Expected behavior
Should be able to use toast on angular 13
## Minimal reproduction of the problem with instructions
Try using toast with HotToastService.
## Environment
<pre><code>
Angular version: 13.0.3
Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v16.13.0
- Platform:Linux
</code></pre>

## Others
```
core.mjs:6484 ERROR Error: 'DynamicViewDirective' is neither 'ComponentType' or 'DirectiveType'.
    at extractDirectiveDef (core.mjs:945)
    at Array.map (<anonymous>)
    at def.directiveDefs (core.mjs:920)
    at createTView (core.mjs:9736)
    at getOrCreateTComponentView (core.mjs:9684)
    at addComponentLogic (core.mjs:10455)
    at instantiateAllDirectives (core.mjs:10296)
    at createDirectivesInstances (core.mjs:9647)
    at Module.ɵɵelementStart (core.mjs:14536)
    at HotToastContainerComponent_hot_toast_4_Template (ngneat-hot-toast.mjs:358)
```

**Comment by hexdecimal16** [comment]
So I figured out the issue I have used:
`ng add @ngneat/hot-toast`
to add the package , now the problem is this installs  `"@ngneat/overview": "^2.0.2"` but the correct version should be     `"@ngneat/overview": "^3.0.0"` for angular 13

**Comment by shhdharmen** [comment]
great! Can you raise PR for that?
