### ISSUE TITLE
Allow using `observe()` for errors only

### ISSUE THREAD

**Issue by aintnomoreloyalty** [ngneat/hot-toast#96]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

When using method `observe()` from `ToastService` it expects `messages` param that has 3 fields: `success` which is required, and `error` and `loading` which are non required. If you try to pass only `error` message, there will be an error because `success` is required.

## Expected behavior

![image](https://user-images.githubusercontent.com/24766748/145420922-eb1bc67b-3fbb-442a-843c-3a67fe794240.png)
ToastService should accept either `success` or `error` message, but `success` should not be required.

## What is the motivation / use case for changing the behavior?

In my case I do not want to display success toasts for all requests, because some of them are very obvious. That's why for some cases there is better to display only error toast if something goes wrong and do not display toast if everything is ok, because UI is going to change, and user will understand what is going on

## Environment

<pre><code>
Angular version: 13.0.0

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 16.13.0
- Platform:  Mac

Others:
</code></pre>

**Comment by aintnomoreloyalty** [comment]
If anyone is interested, I can fix it for sure

**Comment by shhdharmen** [comment]
Sure, please go ahead and raise a PR.
